services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 20060721
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
